DROP TABLE user_roles IF EXISTS;
DROP TABLE menus IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)         NOT NULL,
  email            VARCHAR(255)         NOT NULL,
  password         VARCHAR(255)         NOT NULL,
  is_voted         BOOLEAN   DEFAULT FALSE
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY ( user_id ) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255),
  address         VARCHAR(255) NOT NULL,
  count_of_votes  INT DEFAULT 0
);
CREATE UNIQUE INDEX restaurants_unique_address_idx ON RESTAURANTS (address);

CREATE TABLE menus
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  date              TIMESTAMP NOT NULL,
  description       VARCHAR(255) NOT NULL,
  price             INT NOT NULL,
  restaurant_id     INTEGER NOT NULL,
  FOREIGN KEY ( restaurant_id ) REFERENCES RESTAURANTS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX menus_unique_restaurant_datetime_idx ON menus (restaurant_id, date)